### ISSUE TITLE
Using note field to control duration is not possible.

### ISSUE THREAD

**Issue by roughy** [leanovate/mite-go#1]
Mite has a feature to calculate and set the duration if a special string is given in the note field like `(09:00 bis 18:00)`.
Also if you change the duration eg. to `8h` mite keeps the related string oin the notes field in sync and changes it to `(09:00 bis 17:00)`.

* Version: 0.1.3
* Summary: If I set such string in the notes field to change the duration with the mite-go client it will not update the former duration but will adjust my notes appropriately to the former duration value.
* Steps to reproduce:
  1. `go run main.go entries create -a sonstiges -d 8h`
  2. `go run main.go entries edit -i<12345> -a sonstiges -n "(10:00 bis 11:00)"`
* Expected result: Duration is changed to `1h`, notes field contains my given string `(10:00 bis 11:00)`
* Actual result: Duration stays at `8h`and my notes is changed to `(10:00 bis 18:00)`

**Comment by smoothd** [comment]
Sadly, this appears to be a feature of the mite web client. To replicate the feature we would have to reverse engineer the mite web client logic.
